name: CQueue

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - 'main'

jobs:
    check:
      name: Build & Test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install
          run: |
            sudo apt-get update && sudo apt-get upgrade
            sudo apt-get install build-essential cmake
            git clone https://github.com/google/googletest
            cd googletest && mkdir build
            cd build && cmake .. && make
            sudo make install
        - name: Build and Run
          run: |
            make
            make check
    
